// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3R48k8ivHdXMAmzL5l_LELP8a9UxQCu0',
    appId: '1:908613095209:web:ebf65843dd53f934673138',
    messagingSenderId: '908613095209',
    projectId: 'madcamp-week1-c5354',
    authDomain: 'madcamp-week1-c5354.firebaseapp.com',
    storageBucket: 'madcamp-week1-c5354.appspot.com',
    measurementId: 'G-C343QR8KMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxsSNovqlG1n9Se230r78F8qMsiwyyLnw',
    appId: '1:908613095209:android:f70b44b76e6caf62673138',
    messagingSenderId: '908613095209',
    projectId: 'madcamp-week1-c5354',
    storageBucket: 'madcamp-week1-c5354.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-JzOy60XJJD98vNN_BwfOzS2nrX1vXqA',
    appId: '1:908613095209:ios:7847a2729d1855c3673138',
    messagingSenderId: '908613095209',
    projectId: 'madcamp-week1-c5354',
    storageBucket: 'madcamp-week1-c5354.appspot.com',
    iosBundleId: 'com.example.madcampWeek1Mission',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-JzOy60XJJD98vNN_BwfOzS2nrX1vXqA',
    appId: '1:908613095209:ios:7847a2729d1855c3673138',
    messagingSenderId: '908613095209',
    projectId: 'madcamp-week1-c5354',
    storageBucket: 'madcamp-week1-c5354.appspot.com',
    iosBundleId: 'com.example.madcampWeek1Mission',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3R48k8ivHdXMAmzL5l_LELP8a9UxQCu0',
    appId: '1:908613095209:web:4b8efb6a1acbc560673138',
    messagingSenderId: '908613095209',
    projectId: 'madcamp-week1-c5354',
    authDomain: 'madcamp-week1-c5354.firebaseapp.com',
    storageBucket: 'madcamp-week1-c5354.appspot.com',
    measurementId: 'G-63Z0DHJHL8',
  );

}